config/routes.rb
Rails.application.routes.draw do
  resources :reviewings
  resources :books
  resources :shelves
  devise_for :users
  resources :users

  root 'shelves#index'

  resources :shelves do
    resources :books do
      member do
        get 'remove_book'
        get 'move_book'
      end
    end
  end

  resources :books do
    resources :reviewings
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_and_belongs_to_many :shelves
	has_many :reviewings

	validates :isbn, presence: true, uniqueness: true
	validates :title, presence: true
	def updateRate(id)
		@book = Book.find(id)
		@book.reviews_quantity = @book.reviewings.count
		@book.rates_total = 0

		@book.reviewings.each do |reviewing|
			@book.rates_total += reviewing.rate
		end
		
		@book.save
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_shelf, only: [:create, :move_book, :remove_book]
  before_action :set_book, only: [:create, :edit, :update, :destroy, :set_shelf]

  # GET /books
  # GET /books.json
  def index
    if !params[:search_key].nil?
      user_ip = request.remote_ip # assuming user is accessing from a valid IP address
      @books_result = GoogleBooks.search(params[:search_key], {:count => 36}, user_ip)
      @books = @books_result.reject {|book| book.isbn.blank? || book.image_link.blank? }
    else
      @books = current_user.books if user_signed_in?
    end
    if user_signed_in?
      @shelves = current_user.shelves
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @shelf.books << @book if !@shelf.books.include? @book

    respond_to do |format|
      if @shelf.user.reviewings.where(book_id: @book).empty?
        format.html { redirect_to new_book_reviewing_path(@book), notice: 'Already in shelf.'}
        format.json { render json: @book.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to books_path(search_key: params[:search_key]), notice: 'Book was successfully added to shelf.', search_key: params[:search_key] }
        format.json { render :index, status: :created, location: @book }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_book
    @book = @shelf.books.find(params[:id])
    @shelf.books.delete(@book)

    respond_to do |format|
      format.html { redirect_to shelves_path, notice: 'Book was successfully removed from shelf.' }
      format.json { render :index, status: :created, location: @shelf }
    end
  end

  def move_book
    @book = @shelf.books.find(params[:id])
    @shelf.books.delete(Book.find(params[:id]))
    @new_shelf = Shelf.find(params[:to_shelf_id])
    @new_shelf.books << @book

    respond_to do |format|
      format.html { redirect_to shelves_path, notice: 'Book was successfully removed from shelf.' }
      format.json { render :show, location: @shelf }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.where(isbn: params[:book_isbn]).first
      if @book.nil?
        @book = Book.new
        user_ip = request.remote_ip
        @result = GoogleBooks.search("ISBN:#{params[:book_isbn]}", {}, user_ip).first
        @book.isbn = @result.isbn
        @book.title = @result.title
        @book.image_link = @result.image_link
        @book.published_date = @result.published_date
        @book.authors = @result.authors
        @book.description = @result.description
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn)
    end

    def set_shelf
      if params[:shelf_id]
        @shelf = Shelf.find(params[:shelf_id])
      else
        if !current_user.books.include? @book
          @shelf = Shelf.where(name: 'Leídos').first
        else 
          @shelf = @book.shelves.where(user_id: current_user.id)
        end
      end
    end

end

app/helpers/books_helper.rb
module BooksHelper

	def get_book_rate(book_isbn)
		@book = Book.where(isbn: book_isbn).first
		if @book.nil? || @book.reviews_quantity == 0
			return 1
		else
			@result = (@book.rates_total/@book.reviews_quantity)
			return @result.to_f
		end
	end

	def book_already_in_shelf(book_isbn)
		@book = Book.where(isbn: book_isbn).first
		if @book.nil?
			return false
		else 
			@shelves.each do |shelf| 
				if shelf.books.include? @book
					return true
				end
			end
			return false
		end
	end

	def get_shelf_of_book(book_isbn)
		@book = Book.where(isbn: book_isbn).first
		@shelves.each do |shelf| 
			if shelf.books.include? @book
				return shelf.name
			end
		end
	end

end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p class="notice" id = "notice"><% notice %></p>

<% if !@books.nil? %>
   
   <% if @books.empty? %>
      <p> No books saved yet. </p>
   <% else %>
      <div class="row">
         <% @books.each do |book| %>

            <div class="col s6 m4">
               <div class="card small">

                  <div class="card-image">
                     <img src= <%= book.image_link %>>
                     <span class="card-title"><%= truncate(book.title, length: 50) %></span>
                  </div>

                  <div class="card-content">
                     <p> <%= book.authors %> </p>
                  </div>

                  <div class="card-action">
                     <% if book_already_in_shelf(book.isbn) || !user_signed_in? %>
                        <div class="options-icon col s6 m6 center">
                     <% else %>
                        <div class="options-icon col s4 m4 center">
                           <%= link_to '<i class="material-icons">library_add</i>'.html_safe, books_path(book_isbn: book.isbn, search_key: params[:search_key]), method: :post, :class => 'waves-effect waves-teal' %>
                        </div>
                        <div class="options-icon col s4 m4 center">
                     <% end %>
                           <%= link_to '<i class="material-icons">chat_bubble</i>'.html_safe, book_reviewings_path(book.isbn), :class => 'waves-effect waves-teal' %>
                        </div>

                     <% if book_already_in_shelf(book.isbn) %>
                        <div class="options-icon col s6 m6 center">
                     <% else %>
                        <div class="options-icon col s4 m4 center">
                     <% end %>

                           <a class='waves-effect waves-teal modal-trigger' href= <%="#book-description#{book.isbn}" %> data-activates=''>
                              <i class="material-icons">add</i>
                           </a>
                        </div>
                  </div>
               </div>
            </div>

            <div id= <%= "book-description#{book.isbn}" %> class="modal">
               <div class="modal-content">
                  <h4> <%= book.title %></h4>
                  <p><i>Publicado <%= book.published_date %></i></p>
                  <p>Rate: <%= get_book_rate(book.isbn) %></p>
                  <p> <%= book.description %> </p> <br>

                  <% if !book_already_in_shelf(book.isbn) && user_signed_in? %>
                     <%= form_tag books_path(book_isbn: book.isbn, search_key: params[:search_key]) do %>
                        <h6>Add to shelf:</h6>
                        <div class="row">
                           <div class="input-field col m8 s12">
                              <%= select_tag :shelf_id, options_from_collection_for_select(@shelves, "id", "name") %>
                           </div>
                           <div class="input-field col m4 s12">
                              <button class = "btn" type = "submit">
                                 <i class="material-icons">done</i>
                              </button>
                           </div>
                        </div>
                     <% end %>  
                  <% end %>

               </div>
            </div>

         <% end %>
      </div>
   <% end %>

<% else %>
   <h4> Bienvenido? </h4>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p class="notice" id = "notice"><% notice %></p>
<p>
  <strong>Isbn:</strong>
  <%= @book.id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>