config/routes.rb
Rails.application.routes.draw do
  resources :reviewings
  resources :books
  resources :shelves
  devise_for :users
  resources :users

  root 'shelves#index'

  resources :shelves do
    resources :books do
      member do
        get 'remove_book'
        get 'move_book'
      end
    end
  end

  resources :books do
    resources :reviewings
  end

end

app/models/reviewing.rb
class Reviewing < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  validates :book_id, :user_id, :rate, presence: true
  validates :rate, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 10 }
end

app/controllers/reviewings_controller.rb
class ReviewingsController < ApplicationController
  before_action :set_reviewing, only: [:show, :edit, :update, :destroy]

  # GET /reviewings
  # GET /reviewings.json
  def index
    if params[:book_id]
      @book = Book.where(isbn: params[:book_id]).first
      if !@book.nil?
        @reviewings = @book.reviewings        
      end
    end
  end

  # GET /reviewings/1
  # GET /reviewings/1.json
  def show
  end

  # GET /reviewings/new
  def new
    @reviewing = Reviewing.new
  end

  # GET /reviewings/1/edit
  def edit
  end

  # POST /reviewings
  # POST /reviewings.json
  def create
    @reviewing = Reviewing.new(reviewing_params)
    @book = @reviewing.book
    @user = User.find(current_user.id)
    @user.reviewings << @reviewing
    @book.updateRate(@book.id)

    respond_to do |format|
      if @reviewing.save
        format.html { redirect_to book_reviewings_path(@reviewing.book.isbn), notice: 'Reviewing was successfully created.' }
        format.json { render :show, status: :created, location: @reviewing }
      else
        format.html { render :new }
        format.json { render json: @reviewing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviewings/1
  # PATCH/PUT /reviewings/1.json
  def update
    @book = @reviewing.book
    
    respond_to do |format|
      if @reviewing.update(reviewing_params)
        @book.updateRate(@book.id)
        format.html { redirect_to book_reviewings_path(@reviewing.book.isbn), notice: 'Reviewing was successfully updated.' }
        format.json { render :show, status: :ok, location: @reviewing }
      else
        format.html { render :edit }
        format.json { render json: @reviewing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviewings/1
  # DELETE /reviewings/1.json
  def destroy
    @book = @reviewing.book
    
    @reviewing.destroy
    respond_to do |format|
      @book.updateRate(@book.id)
      format.html { redirect_to reviewings_url, notice: 'Reviewing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reviewing
      @reviewing = Reviewing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reviewing_params
      params.require(:reviewing).permit(:book_id, :rate, :review)
    end
end

app/helpers/reviewings_helper.rb
module ReviewingsHelper

	def user_reviewed_book(book_isbn)
		@book = Book.where(isbn: book_isbn).first
		if current_user.books_reviewed.include? @book
			return false
		else
			return true
		end
	end

	def review_by_user(reviewing_id)
		if current_user.reviewings.find(reviewing_id).nil?
			return false
		else
			return true
		end
	end

	def get_book_reviewed(book_isbn)
		@book = Book.where(isbn: book_isbn).first
		if !@book.nil?
			return @book.title
		else
			user_ip = request.remote_ip # assuming user is accessing from a valid IP address
			@results = GoogleBooks.search(book_isbn, {}, user_ip)
			@book = @results.first
			return @book.title
		end
	end

end

app/views/reviewings/_form.html.erb
<%= form_for(@reviewing) do |f| %>
  <% if @reviewing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reviewing.errors.count, "error") %> prohibited this reviewing from being saved:</h2>

      <ul>
      <% @reviewing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :book_id, :value => params[:book_id] %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviewings/edit.html.erb
<h1>Editing Reviewing</h1>

<%= render 'form' %>

<%= link_to 'Show', @reviewing %> |
<%= link_to 'Back', reviewings_path %>

app/views/reviewings/index.html.erb
<p class="notice" id = "notice"><%= notice %></p>

<div class="row valign-wrapper">
   <div class="col m11">
      <h4>Reviewings for <%= get_book_reviewed(params[:book_id]) %> </h4>
   </div>
   <div class="col m1 valign">
      <% if user_reviewed_book(params[:book_id]) %>
         <%= link_to '<i class="medium material-icons right">add</i>'.html_safe, books_path(book_isbn: params[:book_id]), method: 'post' %>
      <% end %>
   </div>
</div>

<% if @reviewings && !@reviewings.empty? %>
   <table class="responsive-table striped centered">
    <thead>
        <tr>
          <th>User</th>
          <th>Rate</th>
          <th>Review</th>
          <th>Por si las dudas</th>
        </tr>
    </thead>
      <tbody>
         <% @reviewings.each do |reviewing| %>
            <tr>
               <td><b> <%= reviewing.user.email %> </b>
               </td>
               <td><i class = "center"> <%= reviewing.rate %> </i></td>
               <td>
                  <% if reviewing.review.empty? %>
                    <p> - </p>
                  <% else %>
                    <p> <%= reviewing.review %> </p>
                  <% end %>
               </td>
               <% if review_by_user(reviewing.id) %>
                  <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_reviewing_path(reviewing, book_id: reviewing.book.id) %>
                  <%= link_to '<i class="material-icons">delete</i>'.html_safe, reviewing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
               <% end %>
             </tr>
          <% end %>
        </tbody>
   </table>
<% else %>
   <p>No reviews about this book.</p>
<% end %>

app/views/reviewings/new.html.erb
<h1>New Reviewing</h1>

<%= render 'form' %>

<%= link_to 'No, maybe later', shelves_path %>

app/views/reviewings/show.html.erb
<p>
  <strong>Book:</strong>
  <%= @reviewing.book %>
</p>

<p>
  <strong>User:</strong>
  <%= @reviewing.user %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @reviewing.rate %>
</p>

<p>
  <strong>Review:</strong>
  <%= @reviewing.review %>
</p>

<%= link_to 'Edit', edit_reviewing_path(@reviewing) %> |
<%= link_to 'Back', reviewings_path %>